export const languageConstantsForCountry : any = {
    en: {
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
    po: {
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
    ge: {
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
    fr:{
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
    sp: {
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
    du: {
        AddGridData_NumberValueValidation: "Number must have a value between $ and $$",
        AddGridData_StringLengthValidation: "Input must have a length between $ and $$",
        AddGridData_RequiredError: "Required Field",
        AddGridData_DecimalValidation: "Number can have a maximum of $ decimal places",
        AddGridData_DuplicateError: "Duplicates not allowed",
        AddGridData_SaveDataNotify: "Data saved successfully",
        AddGridData_SaveDataError: "Error in saving. Please try again", 
        AddGridData_CommonError: "Something went wrong. Please try again",
        AddGridData_MinNumberValidation: "Number must be greater than $",
        AddGridData_MaxNumberValidation: "Number must be less than $",
        AddGridData_MaxStringValidation: "Input must be less than $",
        AddGridData_MinStringValidation: "Input must be greater than $"
    },
};